"""Unified moment-proposal model.

A MomentProposal is the single canonical object describing one candidate
clip in the highlight reel pipeline. Telemetry highlights, vision-model
hits, Strava segments, and manual labels all map onto this shape. The
reviewer (whichever one is in use) reads + writes proposals; the
composer consumes approved proposals.

Identity is `stable_id` derived from (clip_stem, anchor_video_secs at
1-second precision). Re-running the pipeline does not change the id of
a moment, so reviewer state (selections, ratings, preview cache) and
on-disk artifacts can be keyed by id without drifting.

This module is deliberately small and free of pipeline imports so it
can be loaded without dragging in fitparse, Pillow, or the Gemini SDK.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path


# ─── Status values ──────────────────────────────────────────

STATUS_PENDING = "pending"      # generated by detector, awaiting review
STATUS_APPROVED = "approved"    # user accepted into the cut
STATUS_REJECTED = "rejected"    # user explicitly excluded
STATUS_AUTO = "auto"            # not reviewed; pipeline is in skip-review mode


# ─── Stable id ──────────────────────────────────────────────

def stable_id_for(clip_name: str, anchor_video_secs: float) -> str:
    """Identity that survives pipeline reruns and re-anchoring jitter.

    Identical to composer.stable_id_for — duplicated here so this module
    has no circular dependency on composer.
    """
    stem = Path(clip_name).stem
    return f"{stem}@{int(round(anchor_video_secs))}"


# ─── Model ──────────────────────────────────────────────────

@dataclass
class MomentProposal:
    """One candidate clip with all signals about it.

    review_span = [video_start, video_end]: the window the reviewer scrubs.
    anchor_video_secs: where the final cut centers (the "peak" of the moment).
    final_trim_secs: width of the final cut around the anchor (default 3s).
    user_anchor_override / user_in_out: filled in by the unified reviewer
        when the user manually re-anchors or trims a moment. The composer
        prefers user values over detector values when both exist.
    """

    stable_id: str
    clip_name: str
    video_start: float       # review span start
    video_end: float         # review span end
    anchor_video_secs: float
    ride_time_secs: float

    sources: list[str] = field(default_factory=list)
    score: float = 0.0
    rubric: dict = field(default_factory=dict)
    telemetry_features: dict = field(default_factory=dict)
    portrait_crop_bias: float = 0.0
    final_trim_secs: float = 3.0

    notes: str = ""
    type: str = ""
    star_count: int = 0

    # Reviewer state
    status: str = STATUS_PENDING
    rating: int = 0          # 0=unrated, 1-10
    user_anchor_override: float | None = None
    user_in_out: tuple[float, float] | None = None

    # ── Convenience ─────────────────────────────────────

    @property
    def included(self) -> bool:
        """True if this moment goes into the cut."""
        return self.status in (STATUS_APPROVED, STATUS_AUTO)

    @property
    def effective_anchor(self) -> float:
        """User anchor wins if set, else detector anchor."""
        return self.user_anchor_override if self.user_anchor_override is not None else self.anchor_video_secs

    @property
    def effective_review_span(self) -> tuple[float, float]:
        """User in/out wins if set, else detector span."""
        if self.user_in_out is not None:
            return self.user_in_out
        return (self.video_start, self.video_end)

    # ── Serialization ───────────────────────────────────

    def to_dict(self) -> dict:
        """Plain JSON-serializable dict. Tuples are flattened to lists."""
        d = asdict(self)
        if d["user_in_out"] is not None:
            d["user_in_out"] = list(d["user_in_out"])
        return d

    @classmethod
    def from_dict(cls, d: dict) -> "MomentProposal":
        """Lenient: missing fields fall back to defaults; tuples re-tupled."""
        d = dict(d)  # don't mutate caller's copy
        in_out = d.get("user_in_out")
        if in_out is not None and not isinstance(in_out, tuple):
            d["user_in_out"] = tuple(in_out)
        # Backfill stable_id for old artifacts
        if not d.get("stable_id"):
            d["stable_id"] = stable_id_for(
                d.get("clip_name", ""),
                d.get("anchor_video_secs",
                      (d.get("video_start", 0.0) + d.get("video_end", 0.0)) / 2),
            )
        d.setdefault("sources", [d["source"]] if d.get("source") else [])
        d.pop("source", None)  # legacy single-source field
        # Drop unknown keys so dataclass init doesn't raise
        known = {f for f in cls.__dataclass_fields__}
        d = {k: v for k, v in d.items() if k in known}
        return cls(**d)


# ─── IO ────────────────────────────────────────────────────

def load_proposals(path: Path) -> list[MomentProposal]:
    """Load a list of proposals from JSON. Empty list if file is missing."""
    path = Path(path)
    if not path.exists():
        return []
    raw = json.loads(path.read_text())
    if not isinstance(raw, list):
        return []
    return [MomentProposal.from_dict(d) for d in raw]


def save_proposals(proposals: list[MomentProposal], path: Path) -> None:
    """Write proposals to a JSON file. Sorted chronologically."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    sorted_props = sorted(proposals, key=lambda p: p.ride_time_secs)
    path.write_text(json.dumps([p.to_dict() for p in sorted_props], indent=2))


# ─── Conversion from existing Segment ──────────────────────

def from_segment(seg) -> MomentProposal:
    """Build a MomentProposal from a composer.Segment.

    Pulls notes/type/star_count out of the legacy `label` dict so the
    flat MomentProposal shape replaces it. Leaves status as pending.
    """
    label = getattr(seg, "label", {}) or {}
    return MomentProposal(
        stable_id=seg.stable_id,
        clip_name=seg.clip_name,
        video_start=seg.video_start,
        video_end=seg.video_end,
        anchor_video_secs=seg.anchor_video_secs,
        ride_time_secs=seg.ride_time_secs,
        sources=list(seg.sources) if seg.sources else ([seg.source] if seg.source else []),
        score=seg.score,
        rubric=dict(seg.rubric) if seg.rubric else {},
        portrait_crop_bias=seg.portrait_crop_bias,
        notes=label.get("notes", ""),
        type=label.get("type", ""),
        star_count=int(label.get("star_count", 0) or 0),
        status=STATUS_PENDING,
    )


def proposals_from_segments(segments: list) -> list[MomentProposal]:
    """Convert a list of Segments to MomentProposals, deduped by stable_id."""
    out: dict[str, MomentProposal] = {}
    for seg in segments:
        p = from_segment(seg)
        # If two segments collide on stable_id (rare — anchor within 1s),
        # keep the higher-scoring one and union sources.
        existing = out.get(p.stable_id)
        if existing is not None:
            existing.sources = sorted(set(existing.sources) | set(p.sources))
            if p.score > existing.score:
                existing.score = p.score
                existing.rubric = p.rubric or existing.rubric
                existing.notes = p.notes or existing.notes
            continue
        out[p.stable_id] = p
    return list(out.values())
